//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="FileRelayNativeMethods.cs" company="Quamotion">
// Copyright (c) 2016-2021 Quamotion. All rights reserved.
// Copyright (c) 2022-2024 Wayne Bonnici.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.FileRelay
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public partial class FileRelayNativeMethods
    {
        
        public static FileRelayError file_relay_request_sources(FileRelayClientHandle client, System.Collections.ObjectModel.ReadOnlyCollection<string> sources, out iDeviceConnectionHandle connection)
        {
            System.Runtime.InteropServices.ICustomMarshaler sourcesMarshaler = NativeStringArrayMarshaler.GetInstance(null);
            System.IntPtr sourcesNative = sourcesMarshaler.MarshalManagedToNative(sources);
            FileRelayError returnValue = FileRelayNativeMethods.file_relay_request_sources(client, sourcesNative, out connection);
            return returnValue;
        }
        
        public static FileRelayError file_relay_request_sources_timeout(FileRelayClientHandle client, System.Collections.ObjectModel.ReadOnlyCollection<string> sources, out iDeviceConnectionHandle connection, uint timeout)
        {
            System.Runtime.InteropServices.ICustomMarshaler sourcesMarshaler = NativeStringArrayMarshaler.GetInstance(null);
            System.IntPtr sourcesNative = sourcesMarshaler.MarshalManagedToNative(sources);
            FileRelayError returnValue = FileRelayNativeMethods.file_relay_request_sources_timeout(client, sourcesNative, out connection, timeout);
            return returnValue;
        }
    }
}
