//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="PlistNativeMethods.cs" company="Quamotion">
// Copyright (c) 2016-2021 Quamotion. All rights reserved.
// Copyright (c) 2022-2024 Wayne Bonnici.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Plist
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public partial class PlistNativeMethods
    {
        
        public static void plist_dict_next_item(PlistHandle node, PlistDictIterHandle iter, out string key, out PlistHandle val)
        {
            System.Runtime.InteropServices.ICustomMarshaler keyMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr keyNative = System.IntPtr.Zero;
            PlistNativeMethods.plist_dict_next_item(node, iter, out keyNative, out val);
            key = ((string)keyMarshaler.MarshalNativeToManaged(keyNative));
            keyMarshaler.CleanUpNativeData(keyNative);
        }
        
        public static void plist_dict_get_item_key(PlistHandle node, out string key)
        {
            System.Runtime.InteropServices.ICustomMarshaler keyMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr keyNative = System.IntPtr.Zero;
            PlistNativeMethods.plist_dict_get_item_key(node, out keyNative);
            key = ((string)keyMarshaler.MarshalNativeToManaged(keyNative));
            keyMarshaler.CleanUpNativeData(keyNative);
        }
        
        public static void plist_get_key_val(PlistHandle node, out string val)
        {
            System.Runtime.InteropServices.ICustomMarshaler valMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr valNative = System.IntPtr.Zero;
            PlistNativeMethods.plist_get_key_val(node, out valNative);
            val = ((string)valMarshaler.MarshalNativeToManaged(valNative));
            valMarshaler.CleanUpNativeData(valNative);
        }
        
        public static void plist_get_string_val(PlistHandle node, out string val)
        {
            System.Runtime.InteropServices.ICustomMarshaler valMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr valNative = System.IntPtr.Zero;
            PlistNativeMethods.plist_get_string_val(node, out valNative);
            val = ((string)valMarshaler.MarshalNativeToManaged(valNative));
            valMarshaler.CleanUpNativeData(valNative);
        }
        
        public static void plist_get_data_val(PlistHandle node, out string val, ref ulong length)
        {
            System.Runtime.InteropServices.ICustomMarshaler valMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr valNative = System.IntPtr.Zero;
            PlistNativeMethods.plist_get_data_val(node, out valNative, ref length);
            val = ((string)valMarshaler.MarshalNativeToManaged(valNative));
            valMarshaler.CleanUpNativeData(valNative);
        }
        
        public static PlistError plist_to_xml(PlistHandle plist, out string plistXml, ref uint length)
        {
            System.Runtime.InteropServices.ICustomMarshaler plistXmlMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr plistXmlNative = System.IntPtr.Zero;
            PlistError returnValue = PlistNativeMethods.plist_to_xml(plist, out plistXmlNative, ref length);
            plistXml = ((string)plistXmlMarshaler.MarshalNativeToManaged(plistXmlNative));
            plistXmlMarshaler.CleanUpNativeData(plistXmlNative);
            return returnValue;
        }
        
        public static PlistError plist_to_bin(PlistHandle plist, out string plistBin, ref uint length)
        {
            System.Runtime.InteropServices.ICustomMarshaler plistBinMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr plistBinNative = System.IntPtr.Zero;
            PlistError returnValue = PlistNativeMethods.plist_to_bin(plist, out plistBinNative, ref length);
            plistBin = ((string)plistBinMarshaler.MarshalNativeToManaged(plistBinNative));
            plistBinMarshaler.CleanUpNativeData(plistBinNative);
            return returnValue;
        }
        
        public static PlistError plist_to_json(PlistHandle plist, out string plistJson, ref uint length, int prettify)
        {
            System.Runtime.InteropServices.ICustomMarshaler plistJsonMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr plistJsonNative = System.IntPtr.Zero;
            PlistError returnValue = PlistNativeMethods.plist_to_json(plist, out plistJsonNative, ref length, prettify);
            plistJson = ((string)plistJsonMarshaler.MarshalNativeToManaged(plistJsonNative));
            plistJsonMarshaler.CleanUpNativeData(plistJsonNative);
            return returnValue;
        }
        
        public static PlistError plist_to_openstep(PlistHandle plist, out string plistOpenstep, ref uint length, int prettify)
        {
            System.Runtime.InteropServices.ICustomMarshaler plistOpenstepMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr plistOpenstepNative = System.IntPtr.Zero;
            PlistError returnValue = PlistNativeMethods.plist_to_openstep(plist, out plistOpenstepNative, ref length, prettify);
            plistOpenstep = ((string)plistOpenstepMarshaler.MarshalNativeToManaged(plistOpenstepNative));
            plistOpenstepMarshaler.CleanUpNativeData(plistOpenstepNative);
            return returnValue;
        }
        
        public static PlistError plist_write_to_string(PlistHandle plist, out string output, ref uint length, PlistFormat format, PlistWriteOptions options)
        {
            System.Runtime.InteropServices.ICustomMarshaler outputMarshaler = NativeStringMarshaler.GetInstance(null);
            System.IntPtr outputNative = System.IntPtr.Zero;
            PlistError returnValue = PlistNativeMethods.plist_write_to_string(plist, out outputNative, ref length, format, options);
            output = ((string)outputMarshaler.MarshalNativeToManaged(outputNative));
            outputMarshaler.CleanUpNativeData(outputNative);
            return returnValue;
        }
    }
}
