//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="PlistErrorExtensions.cs" company="Quamotion">
// Copyright (c) 2016-2021 Quamotion. All rights reserved.
// Copyright (c) 2022 Wayne Bonnici.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.Plist
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public static class PlistErrorExtensions
    {
        
        public static void ThrowOnError(this PlistError value)
        {
            if ((value != PlistError.Success))
            {
                throw new PlistException(value);
            }
        }
        
        public static void ThrowOnError(this PlistError value, string message)
        {
            if ((value != PlistError.Success))
            {
                throw new PlistException(value, message);
            }
        }
        
        public static bool IsError(this PlistError value)
        {
            return (value != PlistError.Success);
        }
    }
}
