//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="BtPacketLoggerErrorExtensions.cs" company="Quamotion">
// Copyright (c) 2016-2021 Quamotion. All rights reserved.
// Copyright (c) 2022 Wayne Bonnici.
// </copyright>
#pragma warning disable 1591
#pragma warning disable 1572
#pragma warning disable 1573

namespace iMobileDevice.BtPacketLogger
{
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using iMobileDevice.iDevice;
    using iMobileDevice.Lockdown;
    using iMobileDevice.Afc;
    using iMobileDevice.Plist;
    
    
    public static class BtPacketLoggerErrorExtensions
    {
        
        public static void ThrowOnError(this BtPacketLoggerError value)
        {
            if ((value != BtPacketLoggerError.Success))
            {
                throw new BtPacketLoggerException(value);
            }
        }
        
        public static void ThrowOnError(this BtPacketLoggerError value, string message)
        {
            if ((value != BtPacketLoggerError.Success))
            {
                throw new BtPacketLoggerException(value, message);
            }
        }
        
        public static bool IsError(this BtPacketLoggerError value)
        {
            return (value != BtPacketLoggerError.Success);
        }
    }
}
